### ISSUE TITLE
Database management stage

### ISSUE THREAD

**Issue by zaccomode** [CAB302-2024-ArchiveVault/historian#35]
- [x] Button leading to #31 
- [x] Button leading to #34(once implemented)
- [x] Button to delete database & contents #21
